apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-project
  template:
    metadata:
      labels:
        app: api-project
    spec:
      containers:
        - name: api-project
          image: api-project:latest
          ports:
            - containerPort: 3000
